# AUTOGENERATED! DO NOT EDIT! File to edit: ../export.ipynb.

# %% auto 0
__all__ = ['export_features', 'export_labels', 'save_models']

# %% ../export.ipynb 1
import torch
from pathlib import Path

# %% ../export.ipynb 4
def export_features(fts_data_li, fts_trgt_li, fts_data_path_li, fts_trgt_path_li):

    [torch.save(fts, path) for fts, path in zip(fts_data_li, fts_data_path_li)]
    [torch.save(fts, path) for fts, path in zip(fts_trgt_li, fts_trgt_path_li)]

def export_labels(lbls_data_li, lbls_trgt_li, lbls_data_path_li, lbls_trgt_path_li):

    [torch.save(lbls, path) for lbls, path in zip(lbls_data_li, lbls_data_path_li)]
    [torch.save(lbls, path) for lbls, path in zip(lbls_trgt_li, lbls_trgt_path_li)]

def save_models(model_li):

    folder_path = Path("Model/")
    [torch.save(mdl.state_dict(), folder_path/f"{mdl.name}.pt") for mdl in model_li]
