# AUTOGENERATED! DO NOT EDIT! File to edit: ../gpu.ipynb.

# %% auto 0
__all__ = ['manage_gpu']

# %% ../gpu.ipynb 1
import torch
import gc

# %% ../gpu.ipynb 4
def manage_gpu(verbal= True):

    mmr_reserved = torch.cuda.memory_reserved() / (1024*1024)
    mmr_max = torch.cuda.max_memory_reserved() / (1024*1024)
    pct_reserved = mmr_reserved / mmr_max * 100

    if verbal: print(f"Memory Reserved | {mmr_reserved:.0f} | {mmr_max:.0f} | {pct_reserved:.0f}%")

    gc.collect()
    torch.cuda.empty_cache()
