# AUTOGENERATED! DO NOT EDIT! File to edit: ../log.ipynb.

# %% auto 0
__all__ = ['log_excel', 'precision_at_k_to_dataframe', 'dataframes_to_excel']

# %% ../log.ipynb 1
from pathlib import Path

import pandas as pd
import torch

# %% ../log.ipynb 4
def log_excel(dts_li, model_li, precision_at_k_li, k_li):

    name = [ [dts.name, model.name] for dts in dts_li for model in model_li]
    df_name = pd.DataFrame(name, columns= ["dts", "mdl"])

    precision_at_k_li = torch.round(precision_at_k_li, decimals= 4)
    df_precision_at_k = pd.DataFrame(precision_at_k_li, columns= k_li)
    
    output = pd.concat([df_name, df_precision_at_k], axis= 1)

    log_folder = Path("log/")
    log_name = "log.xlsx"
    log_path = log_folder/log_name
    output.to_excel(log_path)

    return output


# non-original
def precision_at_k_to_dataframe(dts, model, precision_at_k, k_li, idx= 0):

    name = [ [dts.name, model.name]]
    df_name = pd.DataFrame(name, columns= ["dts", "model"], index= [idx])

    precision_at_k = torch.round(precision_at_k, decimals= 4).unsqueeze(0)
    df_precision_at_k = pd.DataFrame(precision_at_k, columns= k_li, index= [idx])

    return pd.concat([df_name, df_precision_at_k], axis= 1)

# non-original
def dataframes_to_excel(df_li):

    output = pd.concat(df_li, axis= 0)

    log_folder = Path("log/")
    log_name = "dataframes_to_excel.xlsx"
    log_path = log_folder/log_name
    output.to_excel(log_path)

    return output
